import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  // 최상위 레이아웃_Next14에 도입된 기술
  children, // page.tsx가 children에 포함
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        루트 레이아웃
        {children}
      </body>
    </html>
  );
}
